Traceback (most recent call last):
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 301, in log_param
    self.store.log_param(run_id, param)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 863, in log_param
    check_run_is_active(run_info)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/entities/run_info.py", line 12, in check_run_is_active
    raise MlflowException(
mlflow.exceptions.MlflowException: The run 0d3262a4ac5549f9a01f740f2ba4e6d6 must be in 'active' lifecycle_stage.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass-reproducibility/scripts/ablation/../train_nichecompass_reference_model.py", line 781, in <module>
    model.train(n_epochs=args.n_epochs,
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass/nichecompass/models/nichecompass.py", line 694, in train
    self.trainer.train(
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass/nichecompass/train/trainer.py", line 330, in train
    mlflow.log_param(attr, attr_value)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 539, in log_param
    MlflowClient().log_param(run_id, key, value)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/client.py", line 852, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 305, in log_param
    raise MlflowException(msg, INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: The run 0d3262a4ac5549f9a01f740f2ba4e6d6 must be in 'active' lifecycle_stage.

The cause of this error is typically due to repeated calls
to an individual run_id event logging.

Incorrect Example:
---------------------------------------
with mlflow.start_run():
    mlflow.log_param("depth", 3)
    mlflow.log_param("depth", 5)
---------------------------------------

Which will throw an MlflowException for overwriting a
logged parameter.

Correct Example:
---------------------------------------
with mlflow.start_run():
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 3)
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 5)
---------------------------------------

Which will create a new nested run for each individual
model and prevent parameter key collisions within the
tracking store.'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 393, in end_run
    MlflowClient().set_terminated(run.info.run_id, status)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/client.py", line 1575, in set_terminated
    self._tracking_client.set_terminated(run_id, status, end_time)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 468, in set_terminated
    self.store.update_run_info(
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 549, in update_run_info
    check_run_is_active(run_info)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/entities/run_info.py", line 12, in check_run_is_active
    raise MlflowException(
mlflow.exceptions.MlflowException: The run 0d3262a4ac5549f9a01f740f2ba4e6d6 must be in 'active' lifecycle_stage.
