Traceback (most recent call last):
  File "/home/aih/sebastian.birk/workspace/projects/nichecompass-reproducibility/scripts/reference_new/../train_nichecompass_reference_model.py", line 415, in <module>
    experiment = mlflow.set_experiment(f"{args.dataset}_{args.model_label}")
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 112, in set_experiment
    client = MlflowClient()
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/client.py", line 66, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 51, in __init__
    self.store
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 55, in store
    return utils._get_store(self.tracking_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/utils.py", line 186, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/utils.py", line 140, in _get_file_store
    return FileStore(store_uri, store_uri)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 153, in __init__
    self._create_experiment_with_id(
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/store/tracking/file_store.py", line 345, in _create_experiment_with_id
    write_yaml(meta_dir, FileStore.META_DATA_FILE_NAME, experiment_dict)
  File "/home/aih/sebastian.birk/miniconda3/envs/nichecompass-test/lib/python3.9/site-packages/mlflow/utils/file_utils.py", line 149, in write_yaml
    raise Exception("Yaml file '%s' exists as '%s" % (file_path, yaml_file_name))
Exception: Yaml file '/home/aih/sebastian.birk/workspace/projects/nichecompass-reproducibility/scripts/reference_new/mlruns/0/meta.yaml' exists as '/home/aih/sebastian.birk/workspace/projects/nichecompass-reproducibility/scripts/reference_new/mlruns/0/meta.yaml
